#@ load("@ytt:data", "data")
---
#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.

fqdn: #@ "jumpbox.{}".format(data.values.domain)

users:
- name: crdant
  gecos: "Chuck D'Antonio"
  groups:
  - users 
  - adm 
  - sudo
  ssh_authorized_keys: #@ data.values.ssh.authorized_keys.crdant
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  lock_passwd: true

## add microsoft package repositories
apt:
  preserve_sources_list: true
  sources:
    microsoft:
      source: #@ data.values.microsoft.repository 
      key: #@ data.values.microsoft.pgp_key
    hashicorp:
      source: #@ data.values.hashicorp.repository 
      key: #@ data.values.hashicorp.pgp_key
    tailscale:
      source: #@ data.values.tailscale.repository
      key: #@ data.values.tailscale.pgp_key

## Update apt database and upgrade packages on first boot
package_update: true
package_upgrade: true

## Install additional packages on first boot
packages:
- ca-certificates
- curl
- zsh
- direnv
- neovim
- python-is-python3
- pip
- packer
- terraform
# - msodbcsql17
# - mssql-tools
# - unixodbc-dev
- tailscale

# install snaps on first boot
snap:
  commands:
  - snap install jq
  - snap install yq
  - snap install git-ubuntu --classic
  - snap install kubectl --classic
  - snap install helm --classic

## write the systemd service file and coredns config
## files
# write_files:

### Run arbitrary commands at rc.local like time
runcmd:
- [ chsh, -s, /usr/bin/zsh, crdant ]
