#@ load("@ytt:data", "data")
---
#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# 
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.

# set up autoinstall

#cloud-config
autoinstall:
  version: 1
  early-commands:
  - systemctl stop ssh # otherwise packer tries to connect and exceed max attempts
  locale: en_US
  keyboard:
    layout: us
  identity:
    hostname: jumpbox-image
    username: ubuntu
    password: #@ data.values.hashed_password
  ssh:
    authorized_keys: #@ data.values.ssh.authorized_keys
    install-server: true
    allow-pw: false
  late-commands:
    - echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu

## add package repositories
apt:
  preserve_sources_list: true
  sources:
    microsoft:
      source: #@ data.values.microsoft.repository 
      key: #@ data.values.microsoft.pgp_key
    hashicorp:
      source: #@ data.values.hashicorp.repository 
      key: #@ data.values.hashicorp.pgp_key
    tailscale:
      source: #@ data.values.tailscale.repository
      key: #@ data.values.tailscale.pgp_key

## Update apt database and upgrade packages on first boot
package_update: true
package_upgrade: true

## Install additional packages on first boot
packages:
- ca-certificates
- curl
- zsh
- direnv
- neovim
- python-is-python3
- pip
- packer
- terraform
# - msodbcsql17
# - mssql-tools
# - unixodbc-dev
- tailscale

# install snaps on first boot
snap:
  commands:
  - snap install jq
  - snap install yq
  - snap install git-ubuntu --classic
  - snap install kubectl --classic
  - snap install helm --classic

