#@ load("@ytt:data", "data")
---
#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.

fqdn: #@ "jumpbox.{}".format(data.values.domain)
ssh_authorized_key: #@ data.values.ssh.authorized_key

password: #@ data.values.hashed_password
chpasswd:
  expire: true

network:
  version: 2
  ethernets:
    # opaque ID for physical interfaces, only referred to by other stanzas
    id0:
      match:
        macaddress: #@ data.values.mac_address
      wakeonlan: true
      dhcp4: true

users:
- default
- name: crdant
  gecos: "Chuck D'Antonio"
  groups:
  - users 
  - adm 
  - sudo
  ssh_import_id: 
  - gh:crdant
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  lock_passwd: true

# Update apt database and upgrade packages on first boot
package_update: true
package_upgrade: true

### Run arbitrary commands at rc.local like time
runcmd:
- [ chsh, -s, /usr/bin/zsh, crdant ]
