#@ load("@ytt:data", "data")
---
#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# 
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.
fqdn: #@ "jumpbox.{}".format(data.values.domain)
ssh_authorized_keys: #@ data.values.ssh.authorized_keys

## don't require a password change since we just set it
chpasswd:
  expire: false

## add package repositories
apt:
  preserve_sources_list: true
  sources:
    microsoft:
      source: #@ data.values.microsoft.repository 
      key: #@ data.values.microsoft.pgp_key
    hashicorp:
      source: #@ data.values.hashicorp.repository 
      key: #@ data.values.hashicorp.pgp_key
    tailscale:
      source: #@ data.values.tailscale.repository
      key: #@ data.values.tailscale.pgp_key
    github:
      source: #@ data.values.github.repository
      key: #@ data.values.github.pgp_key
    kubic:
      source: #@ data.values.kubic.repository
      key: #@ data.values.kubic.pgp_key

## Update apt database and upgrade packages on first boot
package_update: true
package_upgrade: true

## Install additional packages on first boot
packages:
- open-vm-tools
- ca-certificates
- curl
- zsh
- podman
- xz-utils
- direnv
- neovim
- python-is-python3
- pip
- packer
- terraform
- vault
# - msodbcsql17
# - mssql-tools
# - unixodbc-dev
- powershell
- tailscale
- gh

# install snaps on first boot
snap:
  commands:
  - snap install jq
  - snap install yq
  - snap install git-ubuntu --classic
  - snap install kubectl --classic
  - snap install helm --classic

runcmd:
  - curl -L https://carvel.dev/install.sh | bash
  - curl --output /usr/local/bin/mc -L https://dl.min.io/client/mc/release/linux-amd64/mc
  - chmod 755 /usr/local/bin/mc
  - curl -L https://github.com/concourse/concourse/releases/download/v7.6.0/fly-7.6.0-linux-amd64.tgz | tar -C /usr/local/bin -xzf -
  - curl --output /usr/local/bin/fission -L https://github.com/fission/fission/releases/download/v1.15.0/fission-v1.15.0-linux-amd64
  - chmod 755 /usr/local/bin/fission
  - curl -L https://github.com/vmware-tanzu/velero/releases/download/v1.7.1/velero-v1.7.1-linux-amd64.tar.gz | tar -xf /usr/local/bin --strip-components=1 velero-v1.7.1-linux-amd64/velero
  - chmod 755 /usr/local/bin/velero
