#@ load("@ytt:data", "data")
---
#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# 
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.
autoinstall:
  version: 1
  identity:
    hostname: jumpbox
    username: arceus
    password: #@ data.values.hashed_password
  early-commands:
  - sudo systemctl stop ssh
  locale: en_US
  keyboard:
    layout: us
  network:
    network:
      version: 2
      ethernets:
        ens192:
          dhcp4: yes
  storage:
    config:
    - ptable: gpt
      path: /dev/sda
      wipe: superblock
      type: disk
      id: disk-sda
    - device: disk-sda
      size: 1024M
      wipe: superblock
      flag: boot
      number: 1
      grub_device: true
      type: partition
      id: partition-0
    - fstype: fat32
      volume: partition-0
      label: EFIFS
      type: format
      id: format-efi
    - device: disk-sda
      size: 1024M
      wipe: superblock
      number: 2
      type: partition
      id: partition-1
    - fstype: xfs
      volume: partition-1
      label: BOOTFS
      type: format
      id: format-boot
    - device: disk-sda
      size: -1
      wipe: superblock
      number: 3
      type: partition
      id: partition-2
    - name: sysvg
      devices:
      - partition-2
      type: lvm_volgroup
      id: lvm_volgroup-0
    - name: root
      volgroup: lvm_volgroup-0
      size: 12288M
      wipe: superblock
      type: lvm_partition
      id: lvm_partition-root
    - fstype: xfs
      volume: lvm_partition-root
      type: format
      label: ROOTFS
      id: format-root
    - name: home
      volgroup: lvm_volgroup-0
      size: 4096M
      wipe: superblock
      type: lvm_partition
      id: lvm_partition-home
    - fstype: xfs
      volume: lvm_partition-home
      type: format
      label: HOMEFS
      id: format-home
    - name: opt
      volgroup: lvm_volgroup-0
      size: 2048M
      wipe: superblock
      type: lvm_partition
      id: lvm_partition-opt
    - fstype: xfs
      volume: lvm_partition-opt
      type: format
      label: OPTFS
      id: format-opt
    - name: tmp
      volgroup: lvm_volgroup-0
      size: 3072M
      wipe: superblock
      type: lvm_partition
      id: lvm_partition-tmp
    - fstype: xfs
      volume: lvm_partition-tmp
      type: format
      label: TMPFS
      id: format-tmp
    - name: var
      volgroup: lvm_volgroup-0
      size: 4096M
      wipe: superblock
      type: lvm_partition
      id: lvm_partition-var
    - fstype: xfs
      volume: lvm_partition-var
      type: format
      label: VARFS
      id: format-var
    - name: log
      volgroup: lvm_volgroup-0
      size: 4096M
      wipe: superblock
      type: lvm_partition
      id: lvm_partition-log
    - fstype: xfs
      volume: lvm_partition-log
      type: format
      label: LOGFS
      id: format-log
    - name: audit
      volgroup: lvm_volgroup-0
      size: 4096M
      wipe: superblock
      type: lvm_partition
      id: lvm_partition-audit
    - fstype: xfs
      volume: lvm_partition-audit
      type: format
      label: AUDITFS
      id: format-audit
    - path: /
      device: format-root
      type: mount
      id: mount-root
    - path: /boot
      device: format-boot
      type: mount
      id: mount-boot
    - path: /boot/efi
      device: format-efi
      type: mount
      id: mount-efi
    - path: /home
      device: format-home
      type: mount
      id: mount-home
    - path: /opt
      device: format-opt
      type: mount
      id: mount-opt
    - path: /tmp
      device: format-tmp
      type: mount
      id: mount-tmp
    - path: /var
      device: format-var
      type: mount
      id: mount-var
    - path: /var/log
      device: format-log
      type: mount
      id: mount-log
    - path: /var/audit
      device: format-audit
      type: mount
      id: mount-audit
  ssh:
    install-server: yes
    authorized-keys: #@ data.values.ssh.authorized_keys
  late-commands:
  - echo 'arceus ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/arceus
  - curtin in-target --target=/target -- chmod 440 /etc/sudoers.d/arceus

user-data:
  fqdn: #@ "jumpbox.{}".format(data.values.domain)
  ssh_authorized_keys: #@ data.values.ssh.authorized_keys

  ## don't require a password change since we just set it
  chpasswd:
    expire: false

  ## add package repositories
  apt:
    preserve_sources_list: true
    sources:
      microsoft:
        source: #@ data.values.microsoft.repository 
        key: #@ data.values.microsoft.pgp_key
      hashicorp:
        source: #@ data.values.hashicorp.repository 
        key: #@ data.values.hashicorp.pgp_key
      tailscale:
        source: #@ data.values.tailscale.repository
        key: #@ data.values.tailscale.pgp_key

  ## Update apt database and upgrade packages on first boot
  package_update: true
  package_upgrade: true

  ## Install additional packages on first boot
  packages:
  - open-vm-tools
  - ca-certificates
  - curl
  - zsh
  - xz-utils
  - direnv
  - neovim
  - python-is-python3
  - pip
  - packer
  - terraform
  # - msodbcsql17
  # - mssql-tools
  # - unixodbc-dev
  - powershell
  - tailscale

  # install snaps on first boot
  snap:
    commands:
    - snap install jq
    - snap install yq
    - snap install git-ubuntu --classic
    - snap install kubectl --classic
    - snap install helm --classic

  runcmd:
  - curl -L https://carvel.dev/install.sh | bash
