name: tailscale

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Connect to Tailscale
        uses: tailscale/github-action@v1 
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: check for hello.ipn.dev in netmap
        run:
          curl --head https://vcenter.lab.shortrib.net
